.gitignore, README.md, bin/batfish.js, demo/batfish.config.js, demo/src/pages/index.js, lib/build.js, lib/create-batfish-context.js, lib/create-page-module.js, lib/create-webpack-config-base.js, lib/create-webpack-config-client.js, lib/get-pages-data.js, lib/serve-static.js, lib/start.js, lib/validate-config.js, src/scroll-restoration.js
And some changes and fixes that came to mind while writing documentation.
=> Documentation

lib/build.js, lib/generate-sitemap.js, package.json, yarn.lock
=> Generate a simple sitemap

README.md, conf/eslint-browser.json, examples/internal-routing/batfish.config.js, examples/internal-routing/src/pages/index.md, examples/internal-routing/src/pages/letters.js, examples/internal-routing/src/pages/numbers.js, examples/internal-routing/src/wrapper.js, lib/create-batfish-context.js, lib/validate-config.js, package.json, src/find-matching-route.js, src/router.js, yarn.lock
=> Add internal routing example, fix relevant bugs

examples/react-component-pages/batfish.config.js, examples/react-component-pages/package.json, examples/react-component-pages/src/components/wrapper.js, examples/react-component-pages/src/pages/404.js, examples/react-component-pages/src/pages/about.js, examples/react-component-pages/src/pages/blog.css, examples/react-component-pages/src/pages/blog.js, examples/react-component-pages/src/pages/index.js, examples/react-component-pages/src/pages/unpublished.js
Adds an example using React component pages exclusively. It's super simple, let me know if it should be more elaborate.
=> Add example of React component pages

examples/markdown-pages/batfish.config.js, examples/markdown-pages/package.json, examples/markdown-pages/src/pages/red-lipped-batfish.md
=> Add the most minimal markdown example possible

package.json, yarn.lock
Closes #42.
Tried several examples and they all continue to work as expected.
=> Upgrade to Webpack 3

examples/no-config/package.json, examples/no-config/src/pages/index.md, lib/build.js, lib/serve-static.js, lib/start.js
=> Allow undefined rawConfig in public API

src/route-to.js
=> Fix onRouteTo check during static build

README.md, docs/advanced-usage.md, docs/configuration.md, examples/README.md, examples/basic/batfish.config.js, examples/basic/package.json, examples/basic/src/components/page-shell.js, examples/basic/src/pages/index.js, examples/basic/src/style.css, package.json, yarn.lock
- Creates `docs/advanced-usage.md` so we can differentiate between typical use-cases and more advanced usage.
- Adds tables of contents to all the docs.
- Rephrases some things.
- Adds a `basic` example.
=> [WIP] More better docs

package.json, yarn.lock
Webpack v3 is still not ready for us. Was running into a problem with CSS and the extract-text-webpack-plugin. Ugh.
=> Downgrade Webpack

CHANGELOG.md, lib/create-webpack-config-base.js
=> Use Babel, not Webpack, for ES2015 modules

CHANGELOG.md, lib/build.js, lib/css-inlining-worker.js, lib/inline-css.js, lib/start.js, package.json, yarn.lock
=> Try worker-farm

examples/basic/batfish.config.js, examples/basic/src/components/page-shell.js, examples/basic/src/components/wrapper.js, examples/basic/src/pages/404.js, examples/basic/src/pages/index.js, examples/basic/src/pages/markdown-page.md, examples/basic/src/style.css
Closes https://github.com/mapbox/batfish/issues/93
This basic example demos 3 pages:
/example
/example/markdown-page
/404
with the basic options for [configuration](https://github.com/mapbox/batfish/blob/master/docs/configuration.md)
=> WIP basic example

lib/serve-static.js, lib/start.js
Also tweak the logging of stats a bit.
=> Put BrowserSync in offline mode

CHANGELOG.md, docs/configuration.md, examples/appropriate-images/batfish.config.js, examples/initial-experiments/batfish.config.js, examples/internal-routing/batfish.config.js, examples/react-component-pages/batfish.config.js, examples/using-siteOrigin/batfish.config.js, lib/create-webpack-config-base.js, lib/validate-config.js, src/batfish-app.js, src/empty-application-wrapper.js, src/empty-wrapper.js, src/static-render-pages.js, test/__snapshots__/validate-config.test.js.snap, test/validate-config.test.js
=> Change wrapperPath to applicationWrapperPath

CHANGELOG.md, docs/advanced-usage.md, docs/configuration.md, examples/initial-experiments/src/pages/about/index.js, examples/initial-experiments/src/pages/index.js, lib/constants.js, lib/create-batfish-context.js, lib/create-data-modules.js, lib/create-page-module.js, lib/create-webpack-config-base.js, lib/validate-config.js, test/create-page-module.test.js
Closes #130.
The initial-experiments example utilitizes the dataSelectors API, so it changed accordingly.
=> Revise dataSelectors API

CHANGELOG.md, lib/create-webpack-config-client.js, package-lock.json, package.json
@jfurrow I'm hoping this does the trick for you. Can you try it out?
=> Attempt to prevent duplicate Reacts in bundles

CHANGELOG.md, examples/initial-experiments/src/pages/index.js, examples/initial-experiments/src/test.css, lib/compile-stylesheets.js
=> In CSS leave URLs with protocols alone

README.md
Closes #56.
@samanpwbb: What do you think of this attempt to compare Batfish to similar projects?
I tried not to be critical at all, just to describe the motivation. It might mean the section isn't that satisfying — certainly not for somebody who would want a feature chart or something. I also tried to avoid saying something like "Well, when you are going to rely very, very heavily on a tool, it's often best to build it yourself, if you can, so you can also tweak and change it yourself, fitting it to your needs." —— do you think I should just say that? Any other ideas?
=> Comparison with similar projects

CHANGELOG.md, src/public/prefix-url.js, test/prefix-url.test.js
Closes #135.
@lshig for review.
=> Improve prefixUrl for already-prefixed and absolute input

CHANGELOG.md, docs/configuration.md, examples/initial-experiments/src/pages/posts/one.js, examples/internal-routing/src/pages/letters.js, examples/internal-routing/src/pages/numbers.js, lib/create-batfish-context.js, lib/validate-config.js, package-lock.json, package.json, src/router.js, test/__snapshots__/validate-config.test.js.snap
Closes #144.
Changes described in the changelog.
=> Improve link hijacking

docs/configuration.md
Don't know the origin of the error, but seems remark is not at fault.
Closes #150.
=> Fix configuration docs

CHANGELOG.md, CODE_OF_CONDUCT.md, README.md, docs/advanced-usage.md, docs/batfish-modules.md, docs/configuration.md, docs/node-api.md, package.json
Figured out how to pass formatting settings to remark-cli.
=> Better Markdown auto-formatting

CHANGELOG.md, docs/configuration.md, flow-typed/defs.js, package-lock.json, package.json, src/node/create-webpack-config-base.js, src/node/validate-config.js, test/__snapshots__/create-webpack-config-base.test.js.snap
Closes #167.
@lshig for review.
=> Use babel-preset-env and add babelPresetEnvOptions

CHANGELOG.md, src/webpack/public/prefix-url.js, src/webpack/router.js, test/prefix-url.test.js, test/router-prefix-url.test.js
@jfurrow Can you please try this branch and see if it fixes the bug you saw?
=> Remove imports of batfish-internal/context from public modules

bin/batfish.js, src/node/watch-webpack.js, test/watch-webpack.test.js
=> Do not quit dev server on Webpack errors

CHANGELOG.md, examples/miscellany/batfish.config.js, examples/miscellany/src/components/application-wrapper.js, src/node/validate-config.js, test/examples.test.js, test/test-util/jest-setup.js, test/validate-config.test.js
=> More config validation to improve missing file errors

package-lock.json, package.json, src/node/create-webpack-config-client.js, test/__snapshots__/create-webpack-config-client.test.js.snap, test/create-webpack-config-client.test.js
Now it supports parallelism, caching, and ES2015. So let's use it.
=> Use official Uglify Webpack plugin

CHANGELOG.md, README.md, package.json
@lshig @jfurrow do you agree that Batfish has proven stable enough that we should release v1? Do you foresee any need for breaking changes anytime soon?
=> Prepare 1.0.0

CHANGELOG.md, examples/markdown-wrappers/README.md, examples/markdown-wrappers/batfish.config.js, examples/markdown-wrappers/package.json, examples/markdown-wrappers/src/components/markdown-wrapper-a.js, examples/markdown-wrappers/src/components/markdown-wrapper-b.js, examples/markdown-wrappers/src/components/page-wrapper.js, examples/markdown-wrappers/src/pages/index.js, examples/markdown-wrappers/src/pages/markdown-a.md, examples/markdown-wrappers/src/pages/markdown-b.md, examples/markdown-wrappers/src/pages/markdown-c.md, examples/markdown-wrappers/src/pages/markdown-fake-a.md, package-lock.json, package.json
=> Fix Markdown wrappers and add relevant example

CHANGELOG.md, docs/configuration.md, flow-typed/defs.js, src/node/validate-config.js, src/node/write-context-module.js, src/webpack/router.js, test/__snapshots__/validate-config.test.js.snap, test/__snapshots__/write-context-module.test.js.snap, test/router.test.js
=> Add manageScrollRestoration option

.eslintignore, CHANGELOG.md, docs/advanced-usage.md, docs/configuration.md, examples/spa-minimum-static-build/README.md, examples/spa-minimum-static-build/batfish.config.js, examples/spa-minimum-static-build/package.json, examples/spa-minimum-static-build/src/app.js, examples/spa-minimum-static-build/src/pages/index.js, flow-typed/defs.js, src/node/create-webpack-config-static.js, src/node/static-stubs/react-component.js, src/node/validate-config.js, test/__snapshots__/create-webpack-config-static.test.js.snap, test/__snapshots__/validate-config.test.js.snap, test/create-webpack-config-static.test.js
Also add more documentation about options for single-page apps
with minimal static builds.
Closes #242.
=> Add webpackStaticStubReactComponent option

CHANGELOG.md, docs/advanced-usage.md, docs/configuration.md, examples/spa-minimum-static-build/batfish.config.js, examples/spa-minimum-static-build/src/app.js, examples/spa-minimum-static-build/src/style.css, flow-typed/defs.js, src/node/build.js, src/node/validate-config.js, src/webpack/render-html-page.js, src/webpack/static-render-pages.js, test/__snapshots__/render-html-page.test.js.snap, test/__snapshots__/validate-config.test.js.snap, test/build.test.js, test/render-html-page.test.js
=> Add staticHtmlInlineDeferCss option

CHANGELOG.md, package-lock.json, package.json, src/node/error-types.js, src/node/get-loggable-error-message.js, src/node/get-pages-data.js
Closes #250.
Now you get something nice like this:
=> Improve error messages when front matter parsing fails

CHANGELOG.md, docs/configuration.md, flow-typed/defs.js, src/node/build.js, src/node/validate-config.js, test/__snapshots__/validate-config.test.js.snap, test/build.test.js
=> Add sitemap option

CHANGELOG.md, flow-typed/defs.js, flow-typed/webpack.js, src/node/append-task-time.js, src/node/build.js, src/node/get-pages-data.js, src/node/inline-css.js, src/node/non-page-files.js, src/node/now.js, src/node/watch-css.js, src/node/watch-webpack.js, src/node/write-context-module.js, src/webpack/default-not-found.js, src/webpack/render-html-page.js, test/__snapshots__/build.test.js.snap, test/__snapshots__/render-html-page.test.js.snap, test/build.test.js, test/fixtures/get-pages-data-404-js/404.js, test/fixtures/get-pages-data-404-js/index.md, test/fixtures/get-pages-data-404-md/404.md, test/fixtures/get-pages-data-404-md/index.md, test/get-pages-data.test.js, test/write-context-module.test.js
A few commits of smallish improvements.
=> A few small improvements

src/node/create-webpack-config-static.js, test/__snapshots__/create-webpack-config-static.test.js.snap
=> More "externals" in Webpack static build

docs/configuration.md
(closes https://github.com/mapbox/batfish/issues/256)
=> improve includePages documentation

CHANGELOG.md, bin/batfish.js
(closes https://github.com/mapbox/batfish/issues/269)
=> Use number data type for port

CHANGELOG.md, flow-typed/modules.js, src/node/get-port.js, src/node/serve-static.js, src/node/start.js, test/start.test.js
This adds custom logic to show helpful information on what process is using the said port and then process with a random port.
(closes #274)
=> Handle used port gracefully

CHANGELOG.md, src/node/create-webpack-config-static.js, test/__snapshots__/create-webpack-config-static.test.js.snap, test/create-webpack-config-static.test.js
=> Add webpackPlugins to static build

docs/configuration.md, src/node/validate-config.js
This deprecates the SPA mode of Batfish.
=> Deprecate SPA mode

CHANGELOG.md
@katydecorah for review, please. Anything you think is missed?
=> Changelog 2.0.0

docs/configuration.md, src/node/write-context-module.js, test/write-context-module.test.js
This PR replaces all instances of "whitelist" with "allow list."
=> Replace "whitelist" with "allow list"

docs/advanced-usage.md
This PR fixes a very small syntax error in a code example.
=> Fix small syntax error in code example
