mapbox/batfish

- conf/eslint-base.json
This PR is meant to allow for pages to be named `404.*`, the default "route not found" page.
> Allow page filenames to be 404

- README.md
- conf/eslint-base.json
Closes https://github.com/mapbox/batfish/issues/55 and https://github.com/mapbox/batfish/issues/54.
Initially, implementing draft pages and 404s wasn't obvious to me, so I updated the docs, but I'm open to improving the wording more.
> add 404 and draft docs

- examples/using-siteOrigin/batfish.config.js
- examples/using-siteOrigin/package.json
- examples/using-siteOrigin/src/components/wrapper.js
- examples/using-siteOrigin/src/pages/404.js
- examples/using-siteOrigin/src/pages/index.js
- examples/using-siteOrigin/src/pages/page-a.js
- examples/using-siteOrigin/src/pages/page-b.js
- examples/using-siteOrigin/src/wrapper.css
This PR adds an example of `siteOrigin`.
I'm not sure if this is the best example (using `//localhost:8080`), but I couldn't think of anything better that would allow us to use `siteOrigin` in the routes. Any ideas?
> Add siteOrigin example

- docs/recipes.md
- examples/inline-js/batfish.config.js
- examples/inline-js/package.json
- examples/inline-js/src/components/wrapper.js
- examples/inline-js/src/js/inline-me.js
- examples/inline-js/src/pages/index.js
Closes #65.
Because injecting inline JS can be done without additional configuration *but it might not be obvious to a user*, I thought we could add a recipes doc to explain patterns like this.
@lshig for review.
> Add inline-js example and recipes docs

- lib/build.js
- lib/create-prefix-url.js
- lib/generate-sitemap.js
If a user doesn't specify `siteOrigin`, then Batfish will now do the following:
* Throw an error when using `prefixUrl.absolute`
* Skip sitemap generation and display an explanatory message
I also modified `lib/generate-sitemap.js`. I added a try/catch block to fix promise resolution, because it turns out the `sitemap-static` package doesn't accept a callback ([check out the function](https://github.com/tmcw/sitemap-static/blob/master/index.js#L17)).
Closes #43 
@davidtheclark 👀
> Handle unspecified siteOrigin

- docs/advanced-usage.md
- examples/initial-experiments/src/pages/index.js
- lib/create-webpack-config-base.js
- src/router.js
- src/with-location.js
Partially addresses #76.
Adds a `withLocation` higher-order component that you can use to inject an abbreviated Location object into a component's props.
> withLocation higher-order component

- lib/create-webpack-config-base.js
- package.json
- yarn.lock
Closes https://github.com/mapbox/batfish/issues/82.
Documentation for the plugin is here: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types.
Followed documentation for "Via Node API". By default, the `mode` option is `'remove'` so it wasn't included in `create-webpack-config-base.js`.
I tested this plugin by looking at `examples/appropriate-images` in production (build and serve-static). The plugin removes propTypes from JavaScript files, but they are still present in the `source-map` files that are generated by the devtools option. See the following images:
Before plugin added:
After plugin added:
> add transform-react-remove-prop-types plugin for production builds

- lib/validate-config.js
- test/validate-config.test.js
Closes https://github.com/mapbox/batfish/issues/45.
Properties are documented here: https://github.com/mapbox/batfish/blob/master/docs/configuration.md.
Cut a ticket for documentation on `verbose` https://github.com/mapbox/batfish/issues/98
Used existing `lodash` library to compare 2 properties name lists and return the list of properties that don't match.
> add invalid property error

- docs/advanced-usage.md
- examples/initial-experiments/src/pages/index.js
- src/router.js
Closes #113.
Of course there will be no `hash` or `search` during the static build; but now you can expect them to be available even in your component's `componentWillMount` function when that code is running in the browser.
@tristen for review.
> Add search and hash to initial location

- src/router.js
We don't want to scroll to top when the location's pathname is the exact same or if the hash is not present.
> Prevent scrolling to top under certain conditions

- .gitignore
- CHANGELOG.md
- README.md
- examples/basic/src/pages/markdown-page.md
- examples/initial-experiments/src/pages/posts/three.md
- lib/create-webpack-config-base.js
- package-lock.json
- package.json
The change here is that jsxtreme-markdown's `modules` front matter option is now `prependJs`.
> Upgrade jsxtreme-markdown

- CHANGELOG.md
- README.md
- docs/configuration.md
- lib/create-webpack-config-client.js
- lib/validate-config.js
- package.json
- test/__snapshots__/validate-config.test.js.snap
I decided that the Promise polyfill is important enough (neither Webpack dynamic imports nor Batfish's router are designed to work without it) that we should still include it by default. I think that's also the safer bet, since *not* including a polyfill when you do need one is an easy mistake to make and to miss (you have to actually check in IE11).
- Adds an `includePromisePolyfill` option you can set to `false` if you want to use a different Promise polyfill.
- Uses `require.resolve` to add the polyfill to `vendorModules`, so it will always get Batfish's version. (Did the same thing for other default `vendorModules` that are not `peerDependencies`.)
Closes #128.
> Smarten up about es6-promise polyfill inclusion

- CHANGELOG.md
- lib/compile-stylesheets.js
Turns out things need to be a little more complicated for the static build, because the CSS might reference its assets from either inlined CSS, directly in the HTML, or from the stylesheet that lazily loads. So we need the URLs to be root-relative.
Before, the static build for the initial-experiments example gave 404s for fonts. Now, both start and build should work.
> Fix CSS asset copying and referencing for static build

- CHANGELOG.md
- src/public/with-location.js
This PR renames the key on which the original component is provided from `WrapperComponent` to `WrappedComponent`.
Closes #146 
@davidtheclark for review, please!
> Rename WrapperComponent to WrappedComponent in with-location

- examples/using-siteOrigin/src/pages/404.js
Fix prefixUrl import in `using-siteOrigin` example
> Fix prefixUrl import in `using-siteOrigin` example

- CHANGELOG.md
- src-node/start.js
Closes #60.
@jfurrow for review. When you `start`, rebuilds should now happen when you change front matter, add a new page and save some content, or delete a page.
> Watch page files for front matter changes, additions, and deletions

- CHANGELOG.md
- README.md
- bin/batfish.js
- docs/advanced-usage.md
- examples/page-specific-css/README.md
- examples/page-specific-css/package.json
- examples/page-specific-css/src/pages/another.css
- examples/page-specific-css/src/pages/another.md
- examples/page-specific-css/src/pages/index.css
- examples/page-specific-css/src/pages/index.js
- flow-typed/webpack.js
- package-lock.json
- package.json
- src/node/compile-stylesheets.js
- src/node/create-webpack-config-base.js
- src/node/get-postcss-plugins.js
- src/node/page-specific-style-loader.js
- src/node/react-helmet-postcss-loader.js
- src/node/validate-config.js
- test/__snapshots__/validate-config.test.js.snap
Use the latest version of react-helmet (with synchronous tags) to introduce a system for page-specific CSS.
Page-specific CSS should be 
- Processed through the user's PostCSS plugins.
- Minified for the production build.
- Inlined in the page's static HTML.
- Included only in the JS bundles that use it, not in the site-wide stylesheet.
I added another example to illustrate how to import and use a page-specific stylesheet.
@lshig for review.
> Page-specific CSS

- docs/configuration.md
- flow-typed/defs.js
- src/node/build-html.js
- src/node/build.js
- src/node/constants.js
- src/node/create-webpack-config-base.js
- src/node/get-postcss-plugins.js
- src/node/start.js
- src/node/validate-config.js
- test/__snapshots__/validate-config.test.js.snap
- test/build-html.test.js
- test/build.test.js
- test/compile-stylesheets.test.js
- test/start.test.js
- test/validate-config.test.js
`assets` folder can now be customized by setting `publicAssetsPath` in batfish.config.
This closes https://github.com/mapbox/batfish/issues/191
> Allow assets path to be configurable

- .flowconfig
- CHANGELOG.md
- package-lock.json
- package.json
- src/webpack/batfish-app.js
- test/__snapshots__/render-html.test.js.snap
- test/test-util/jest-setup.js
- test/test-util/raf.js
There was one slight change to make, to take advantage of React 16 if the user is using it: use `ReactDOM.hydrate` if it's available, for the static build.
Also, improved errors messages caught a mistaken `shouldComponentUpdate` in `batfish-app.js`.
All other changes are just dependency updates (and the little test tweaks that go along with updating React and Enzyme).
This should be fully backwards compatible, as well: uses React 15 or 16, depending on what the user has installed.
> Allows React 16, updates all dependencies

- package-lock.json
- src/node/create-webpack-config-client.js
- src/node/write-context-module.js
- test/__snapshots__/create-webpack-config-client.test.js.snap
- test/__snapshots__/write-context-module.test.js.snap
Closes #184.
Introduces HashedModuleIdsPlugin and sorts routes in the context module.
I experimented in the examples with this and the results are looking good. When I modify a single page, only that's page bundle's hash changes. When I modify a component shared by 4 pages, only the app bundle's hash changes. And so on. Seems to be working exactly as we'd hope.
> Improve filename hashing for long-term caching

- .travis.yml
- package-lock.json
- package.json
- src/node/create-webpack-config-client.js
- test/__snapshots__/create-webpack-config-client.test.js.snap
Here's a problem we ran into: As pages (or other dynamic `import()`s) are added and removed from the site, those changes to the total number of chunks affects the chunk ids, which are just incremented numbers. And the filename hashes do not change when only chunk ids have changed. So we'd end up with a file like `thing-19dc7283a6f46da29b1c.chunk.js` whose *filename does not change*, but whose *chunk id does change*. This ends up causing mismatches between the manifest and chunk id within the file, leading to chunks failing to load.
I was able to reproduce the problem in the `basic` example by running on build, saving those files, then adding another page `test.md` and running another build, saving those files. Comparing the two files, you'll see that the `markdown` page's chunk file has …
> Introduce NamedChunksPlugin to fix hashing and caching

- CHANGELOG.md
- package-lock.json
- package.json
- src/node/server-init-message.js
I noticed that recent installations got newer versions of BrowserSync that changed the internals of the server instance in a way that broke logging. This PR addresses that.
> Upgrade BrowserSync and fix incompatibilities with instance internals

- CHANGELOG.md
- src/node/create-webpack-config-client.js
I ran into this bug when I dynamically `import()`ed something huge, without providing a name for the Webpack async chunk.
> Prevent hashes for NamedChunksPlugin that are too long for filenames

- CHANGELOG.md
- package-lock.json
- package.json
- src/node/create-webpack-config-base.js
- test/__snapshots__/create-webpack-config-base.test.js.snap
Webpack no longer needs this to import JSON.
Closes #202.
Verified that this works by tinkering with some JSON in the demos.
> Remove json-loader

- CHANGELOG.md
- docs/configuration.md
- flow-typed/defs.js
- package-lock.json
- package.json
- src/node/create-webpack-config-base.js
- src/node/validate-config.js
- test/__snapshots__/create-webpack-config-base.test.js.snap
- test/__snapshots__/validate-config.test.js.snap
- test/create-webpack-config-base.test.js
Also includes a very tiny commit for using `babel-loader`'s default location.
@elifitch for review.
I'd love your input on the `babelInclude` decisions. In #218 I was thinking of adding `compileConditions` and `compileNodeModules`, but after thinking more I decided I'd just add a `babelInclude` option and that would cover the use cases.
You'll end up with a [`Rule.resource`](https://webpack.js.org/configuration/module/#rule-resource) for the JS-related Babel compilation that should:
- Accept `.js(x)` files outside of `node_modules`.
- Accept `.js(x)` files inside `node_modules/@mapbox/batfish`.
- Accept `.js(x)` files that *also* match whatever conditions you pass into `babelInclude`.
- Reject everything else.
I hope that the docs I added to `configuration.md` explain how you can use …
> babelInclude option

- CHANGELOG.md
- src/node/create-webpack-config-client.js
- src/node/create-webpack-config-static.js
- test/__snapshots__/create-webpack-config-client.test.js.snap
This allows the user to import more dependencies with fewer
errors. A dependency can import a library like "fs" without
an error -- the error will only come if they try to use the
library within the code that the user's app ends up executing.
Closes #241.
> Client-side Webpack sets core Node libraries to "empty"

- CHANGELOG.md
- package-lock.json
- package.json
- src/node/create-webpack-config-base.js
- test/__snapshots__/create-webpack-config-base.test.js.snap
Recent versions of Webpack do not require this module for
deterministic filename hashing.
> Remove webpack-chunk-hash dependency

- CHANGELOG.md
- README.md
- docs/advanced-usage.md
- examples/table-of-contents/README.md
- examples/table-of-contents/batfish.config.js
- examples/table-of-contents/package.json
- examples/table-of-contents/src/components/markdown-wrapper.js
- examples/table-of-contents/src/pages/index.md
- flow-typed/defs.js
- package-lock.json
- package.json
- src/node/create-webpack-config-base.js
- test/__snapshots__/create-webpack-config-base.test.js.snap
Uses [a new feature of jsxtreme-markdown](https://github.com/mapbox/jsxtreme-markdown/tree/master/packages/jsxtreme-markdown#headings) to automatically include in Markdown page front matter some data about headings that you can use to generate a table of contents in your Markdown wrapper component.
@colleenmcginnis: I'd love a review from you. Mostly I'm just turning on a feature of jsxtreme-markdown, so the changes here are about documentation and exemplification, which pertain to you since you'll be using the feature right away 😄
> Include data about headings in Markdown pages for ToC generation

- CHANGELOG.md
- docs/configuration.md
- examples/optimizing-loaders/batfish.config.js
- examples/optimizing-loaders/src/pages/index.js
- package-lock.json
- src/node/get-postcss-plugins.js
- src/node/index.js
- test/__snapshots__/compile-stylesheets.test.js.snap
- test/compile-stylesheets.test.js
Changelog entries:
- Feature: Files reference as URLs in CSS then copied into the output directory (via postcss-url) now include the file's original basename as well as the hash.
- Feature: Expose Batfish's version of Webpack on `require('@mapbox/batfish').webpack`, so it can be used for custom plugin configuration.
That second item closes #278. I did not end up putting `webpack` into the config function's arguments because I realized that that would make it unavailable to the Node API. Probably nobody uses the Node API — but I wanted to save that discussion for another day.
@kepta once I get the green light here I'll merge and cut a release, which will include your recent improvements.
> Better CSS asset filenames and exposing Batfish's version of Webpack

- CHANGELOG.md
- src/node/get-pages-data.js
- test/get-pages-data.test.js
If you had a `siteBasePath` and created a custom 404 page, you'd get some weird build errors: the `_404.js` file in the temporary directory was getting all scrambled. The root cause was that the 404 logic in `getPagesData` didn't take `siteBasePath` into account. This fixes that.
> Fix custom 404 pages on sites with a siteBasePath

- CHANGELOG.md
- package-lock.json
- package.json
- test/__snapshots__/create-webpack-config-client.test.js.snap
See https://github.com/ztoben/assets-webpack-plugin/issues/118 about the regression.
I don't think we'll have any need to update this plugin until we try to move to Webpack 4 anyway.
> Set exact assets-webpack-plugin version to avoid regression

- CHANGELOG.md
- src/node/create-webpack-config-client.js
- test/__snapshots__/create-webpack-config-client.test.js.snap
While rolling out Webpack 4 in Batfish, we hit a stopping point with mapbox-gl-js-docs where JavaScript would run out of memory on `build`.
* We fixed one problem where the site was burning memory to generate the stats.json file. #307 
* The build script appears to fail at the terser plugin (minification) because the chunks are too large. This PR attempts to fix that by increasing `maxInitialRequests` and `maxAsyncRequests` to 10 - this will create more chunks at manageable size.
- https://engineering.wingify.com/posts/demystifying-split-chunks-plugin/
- https://engineering.seagroup.com/shopee-webpack4/
Testing to do:
> increase maxAsyncRequests and maxInitialRequests

- CHANGELOG.md
- src/node/create-webpack-config-client.js
- test/__snapshots__/create-webpack-config-client.test.js.snap
Per https://github.com/mapbox/batfish/pull/317#discussion_r323396653 the previous commit and release which increased `maxAsyncRequests` and `maxInitialRequests` in `splitChunks` to prevent JavaScript from running out of memory is not an ideal long term solution as it deteriorates performance on older devices. 
This PR reverts that commit. We'll be looking for a better solution that will not affect build times on the client and prevent running out of memory on `build`. 
In the meantime, we can increase node's memory with:
```
"build": "NODE_OPTIONS=--max-old-space-size=2048 batfish build"
```
> Revert #317 

- src/node/postcss-absolute-urls.js
- test/__snapshots__/postcss-absolute-urls.test.js.snap
- test/postcss-absolute-urls.test.js
We found a bug where the Mapbox logo in Firefox appears warped:
This is caused by postcss-absolute-urls appending the stylesheet url to `mask`. This PR will prevent the plugin from add an absolute url path to urls that begin with `%23clip`.
To see the bug in action, check out the snapshot in 9f829ca and then see how it removes the absolute url from `mask` in the snapshot: 6a9db10
> Skip urls that begin with `%23clip` in postcss-absolute-urls

- .travis.yml
Since this repository defines `.nvmrc`, we do not also need to define `node_js` in travis.yml.
> Remove node_js version from travis.yml

- src/node/get-postcss-plugins.js
- src/node/postcss-absolute-urls.js
- test/__snapshots__/compile-stylesheets.test.js.snap
- test/__snapshots__/postcss-absolute-urls.test.js.snap
- test/fixtures/stylesheets/mapbox-gl.css
- test/postcss-absolute-urls.test.js
This PR fixes a mishap in #364 where the fix was improperly employed to the plugin that serves absolute urls, when it should happen on the plugin that serves relative urls.
In this PR, Batfish will decode the `asset.url` and  then, in addition to absolute paths,  it will skip hashes. This will prevent a relative path from being appended to `mask` paths.
- This commit shows the bug: 5b73dfc
- This commit shows the fix: af24122
This PR will also revert #364
> Update postcss plugins to skip hashes
